### ISSUE TITLE
Increase quantity in cart if the same item is added

### ISSUE THREAD

**Issue by ghost** [bsubedi26/ng2-ShoppingCart#1]
Hi dear author.

I had tested your application and it worked fine. 
However, how can I modify so every time when the user add the same item, it will increase the quantity but not like add a new item into cart, or if user add new item, it will add the new item.

I hope you can understand what I am talking about. Thanks

**Comment by bsubedi26** [comment]
Hi jkTANdeveloper,

Although it can be improved, I have added the functionality where the quantity of the product updates when specifying the amount to add to the cart. I will close this issue for now.
