### ISSUE TITLE
Error: Data must be a string or buffer

### ISSUE THREAD

**Issue by pratik-trianz** [bsubedi26/ng2-ShoppingCart#3]
I am getting this error plz see scrennshot
![shopingcart](https://user-images.githubusercontent.com/26106016/27944921-9eb282d8-6307-11e7-95fa-8ea5d37b3f55.PNG)

**Comment by bsubedi26** [comment]
Hey Pratik, that could be a node issue. What node version are you currently running?

**Comment by ashishbedicn** [comment]
Hi @bsubedi26 . I am also getting this error. I updated the node version to 8.1.4 but its still giving error like this:
```
 86% hashingcrypto.js:97                                                                
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer 86% hashingcrypto.js:97                                                                
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
```

**Comment by pratik-trianz** [comment]
Hey @bsubedi26  I am on Node v6.10.2 & NPM v3.10.10

**Comment by saberhamidi** [comment]
I have the same problem

**Comment by bsubedi26** [comment]
Can you try to pull the latest code from the master branch? Just updated to latest version of angular, @ngrx and other dependencies. It solved this issue on my end. Let me know if it works for you as well.

**Comment by saberhamidi** [comment]
yeah its working fine now, thanks
